### ISSUE TITLE
No audio in Strife: Veteran Edition

### ISSUE THREAD

**Issue by chungy** [clementgallet/libTAS#106] opened 2018-11-03 14:05 UTC
Using this game: https://www.gog.com/game/strife_veteran_edition

libTAS doesn't capture any audio from the game at all.

**Comment by clementgallet** [comment] 2018-11-05 11:50
I tested the open-source engine chocolate-strife, which is supposed to be the same as the gog version. There is a softlock with the OPL SDL driver, which register a callback to the SDL_mixer thread, but it is never called because time does not advance.

**Comment by chungy** [comment] 2018-11-06 04:17
Chocolate Strife is far from the same thing, it uses SDL2 and lacks the OpenGL-based renderer. You really need to test the actual game.

You could potentially use https://github.com/svkaiser/strife-ve instead of the binary release, but it would still require that you own SVE...

**Comment by clementgallet** [comment] 2019-01-28 17:58
I finally tested strife-ve open-source engine with SVE data. The game first extracts a midi file from the game data files, write it in `/tmp/doom.mid`, and make fluidsynth play it through SDL_mixer callback mechanism. When `Backup savefiles in memory` option is checked, this midi file is stored in memory instead, and it messes up its playback. So turning off this option works for me.

**Comment by chungy** [comment] 2019-02-10 16:52
Just trying with 1.3.3 (plus the post-release patch), seems that there is a new problem, libTAS fails at recording Strife at all now; testing the Shovel Knight TAS, it works, but fails on Strife.

```
[libTAS f:1] Thread 24588 (main) ERROR: 0 == av_opt_set_int(swr, "in_channel_layout", AV_CH_LAYOUT_STEREO, 0) failed in mixWith
[nut @ 0x5555555ccec0] No main startcode found.
pipe:: Invalid data found when processing input```

**Comment by clementgallet** [comment] 2019-02-10 19:05
I'm getting another error on this game: 
```
Thread 1 "strife-ve" received signal SIGSEGV, Segmentation fault.
0x00007ffff7c5bd2a in SDL_WM_SetIcon () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
(gdb) bt
#0  0x00007ffff7c5bd2a in SDL_WM_SetIcon () at /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#1  0x00005555555b17ca in I_InitWindowIcon ()
#2  0x00005555555b2830 in I_InitGraphics ()
#3  0x00005555555ec9e5 in D_InitFrontend ()
#4  0x00005555555ed4dc in D_DoomMain ()
#5  0x00005555555a7297 in main ()
```

It's because in `get_sdlversion()` we execute `dlsym(RTLD_DEFAULT, "SDL_GetVersion")`. Even if the program uses SDL1, it links to the SDL2 library because of SDL_mixer (at least debian's version ; still don't know why), so the above call succeeded and the SDL2 library is loaded and `SDL_DYNAPI_entry()` is called, initializing a bunch of SDL2 function pointers.

**Comment by clementgallet** [comment] 2019-02-10 19:19
Fixed in 6b730a57788bf2c0cc08f36e72cbe7be6823f96c. It looks like a completely different bug, but I can't reproduce yours. When you say "recording", you mean dumping the video? Do you also have a crash if you unmute the audio in the tool?

**Comment by chungy** [comment] 2019-02-10 20:46
> Even if the program uses SDL1, it links to the SDL2 library because of SDL_mixer (at least debian's version

What is "Debian's version"? The binaries included with the game only use SDL_mixer 1.2 and SDL1, no linking to SDL2 happens.

> When you say "recording", you mean dumping the video? Do you also have a crash if you unmute the audio in the tool?

Yes, I meant dumping the video. Also yes, it crashes if I unmute the audio (so I guess the latter is unrelated to video recording).

**Comment by clementgallet** [comment] 2019-02-10 21:35
> What is "Debian's version"? The binaries included with the game only use SDL_mixer 1.2 and SDL1, no linking to SDL2 happens.
I'm using the open-source strife-ve engine, with the WADs from the game, so it is using my system libraries, as opposed to the full game being bundled with all required libraries I guess. My (system) SDL_mixer 1.2 library links to SDL2:
```
$ ldd /usr/lib/x86_64-linux-gnu/libSDL_mixer-1.2.so.0
	libSDL2-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007f429a64a000)
```

> Yes, I meant dumping the video. Also yes, it crashes if I unmute the audio (so I guess the latter is unrelated to video recording).
That is an error from the audio resampling code, which didn't happen before because the game disabled audio after getting the bug. I'm not sure what is the cause. Which distribution are you using? Also, could you check if you have sound in other games (Shovel Knight for example)? Because it doesn't sound like a game-specific bug.

**Comment by chungy** [comment] 2019-02-11 05:02
> Which distribution are you using? Also, could you check if you have sound in other games (Shovel Knight for example)? Because it doesn't sound like a game-specific bug.

I am using Arch Linux, and sound indeed works in Shovel Knight.

**Comment by clementgallet** [comment] 2019-02-11 11:15
I could reproduce the bug with the GOG version of S:VE. I think the reason is that the game is bundled with libavutil library, and it may be used in place of our system libavutil for audio resampling, resulting in a crash.

**Comment by chungy** [comment] 2019-02-13 22:43
Is there any reason the encoder has to have the same LD_PRELOAD as the game (or whatever is being done to load libraries)?

**Comment by clementgallet** [comment] 2019-02-13 23:26
We only preload libtas.so but it depends on libavutil.so.56, and strife-ve depends on libavutil.so.54, both exporting the same symbols. I don't know very well how the linker manage all that.

**Closed** 2019-12-20 13:17 UTC
Labels: game-specific, library
