### ISSUE TITLE
Half-Life sometimes randomly hangs

### ISSUE THREAD

**Issue by YaLTeR** [clementgallet/libTAS#342] opened 2020-05-15 07:40 UTC
With this spammed into the terminal:
```
[libTAS f:156] Thread 64 (main) ERROR: Unknown message received
[libTAS f:157] Thread 64 (main) ERROR: Unknown message received
[libTAS f:158] Thread 64 (main) ERROR: Unknown message received
[libTAS f:159] Thread 64 (main) ERROR: Unknown message received
[libTAS f:160] Thread 64 (main) ERROR: Unknown message received
```
for a whole bunch of frames, and then it just hangs. During this time libTAS seems to continue sending mouse input for one frame (presumably the last good one).

Fedora 32, I've seen this on both GNOME Wayland and Xorg sessions. libTAS is running under the Steam flatpak from Flathub with the `org.kde.Platform//5.14` runtime (this part is weird but I have to do it for my TASes to sync since apparently Fedora's libm or whatever is slightly different so I'm running HL under flatpak where it does sync).

**Comment by clementgallet** [comment] 2020-07-13 13:02
Should be fixed in 2c1ed75. Was caused by a signal interrupting the socket message between libtas program and the game.

**Closed** 2020-10-07 13:03 UTC
