### ISSUE TITLE
Segmentation fault(core dumped) on opening

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#168] opened 2019-02-08 23:02 UTC
With the new release, if I run the program, a segmentation fault occurs.

I DID delete .libtas before installing, so that might have made a difference. Installing latest interim gives same result.

Running ubuntu 18.04.1 64-bit

**Comment by Noahkiq** [comment] 2019-02-08 23:03
can reproduce

**Comment by Noahkiq** [comment] 2019-02-08 23:19
quick bisect shows seg fault is being caused by 8515a00

**Comment by clementgallet** [comment] 2019-02-08 23:38
Yes, `getenv` can return null and building a std::string from null is not allowed. Fixed in 5ca20a59239bc1852df5d410ca043ca6a5ea8283

**Comment by Noahkiq** [comment] 2019-02-08 23:51
should probably rerelease 1.3.3 with this fix ;p

**Comment by clementgallet** [comment] 2019-02-08 23:54
Yes, I updated the compiled files

**Comment by vadosnaprimer** [comment] 2019-02-08 23:58
Might be also worth an extra forum post telling to redownload.

**Comment by clementgallet** [comment] 2019-02-10 18:34
Done.

**Closed by clementgallet** 2019-02-10 18:34 UTC
