### ISSUE TITLE
Fast forwarding with an empty input file causes the tool to freeze

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#84] opened 2018-10-08 20:58 UTC
When playing meatboy

**Comment by clementgallet** [comment] 2018-10-10 09:16
Could you write a detailed procedure for how to reproduce this bug ? I'm not getting any issue.

**Comment by Matte27** [comment] 2018-10-11 00:34
1. Select the meatboy executable
2. Create a new empty movie file
3. Set to recording with fast-forward activated (with skipping all rendering)
4. After starting the tool quickly becomes unresponsive and can't be paused/ set to non-ff

**Comment by clementgallet** [comment] 2018-10-12 14:35
Fixed in d067d406357103a881f257f9cd1f1f5e741013b4. The UI was constantly rebuilding the input editor data because there was no input, and couldn't keep the pace because of the fast-forward. Now it only builds on the first frame.

**Closed by clementgallet** 2018-10-12 14:35 UTC
